title: Shrungashree C
logo: assets/shru.png
description: 
 To obtain a Software Engineer position at AskmeOffers, leveraging my skills in software 
 development and machine learning to contribute to innovative solutions and enhance user 
 experiences through personalised recommendations
 
 <a href="https://www.linkedin.com/in/shrungashree-c/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
