title: Shrungashree C# your name (or website title) here
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 To obtain a Software Engineer position at AskmeOffers, leveraging my skills in software 
 development and machine learning to contribute to innovative solutions and enhance user 
 experiences through personalised recommendations
  <br><br>
 Master of Computer Applications (MCA), Vivekananda college of engineering and technology 
 Year of Graduation: 2023
  <br><br>
  <a href="https://www.linkedin.com/in/shrunga-shree-647253176/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
